# Generated by Django 3.0.7 on 2020-07-24 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radio_main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cover',
            old_name='songspy',
            new_name='songs',
        ),
    ]
