# Generated by Django 3.0.7 on 2020-07-11 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio_main', '0002_auto_20200708_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='url',
            field=models.CharField(max_length=300),
        ),
    ]
