# Generated by Django 3.0.7 on 2020-07-24 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('radio_main', '0002_auto_20200724_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cover',
            name='songs',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='radio_main.Song'),
        ),
    ]
