# Generated by Django 3.0.7 on 2020-07-11 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio_main', '0003_auto_20200711_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='img',
            field=models.ImageField(default='', upload_to='img'),
        ),
    ]
