# Generated by Django 3.0.7 on 2020-07-24 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('radio_main', '0004_remove_cover_songs'),
    ]

    operations = [
        migrations.AddField(
            model_name='cover',
            name='songs',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='radio_main.Song'),
        ),
    ]
