# Generated by Django 3.0.7 on 2020-07-11 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio_main', '0004_song_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='img',
            field=models.ImageField(default="D:\\programs\\MUSIC\\David August\\D'ANGELO\\cover.jpg", upload_to='img'),
        ),
    ]
