# Generated by Django 3.0.7 on 2020-07-24 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio_main', '0005_cover_songs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cover',
            name='url',
            field=models.ImageField(upload_to='static/img'),
        ),
    ]
