# Generated by Django 3.0.7 on 2020-07-11 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio_main', '0005_auto_20200712_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='img',
            field=models.ImageField(default='def.jpg', upload_to='img'),
        ),
    ]
