# Generated by Django 3.0.7 on 2020-07-24 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radio_main', '0006_auto_20200724_2347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cover',
            old_name='url',
            new_name='img',
        ),
    ]
