# Generated by Django 3.0.7 on 2020-07-11 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radio_main', '0006_auto_20200712_0029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='url',
        ),
    ]
