# Generated by Django 3.0.7 on 2020-07-11 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio_main', '0007_remove_song_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Covers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=300)),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='song',
            name='img',
        ),
        migrations.AddField(
            model_name='song',
            name='url',
            field=models.CharField(default='default', max_length=300),
            preserve_default=False,
        ),
    ]
