# Generated by Django 3.0.7 on 2020-07-24 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio_main', '0007_auto_20200724_2347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cover',
            name='songs',
        ),
        migrations.AddField(
            model_name='cover',
            name='songs',
            field=models.ManyToManyField(to='radio_main.Song'),
        ),
    ]
