# Generated by Django 3.0.7 on 2020-07-11 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radio_main', '0008_auto_20200712_0037'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Covers',
            new_name='Cover',
        ),
    ]
