# Generated by Django 3.0.7 on 2020-07-12 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio_main', '0010_auto_20200712_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cover',
            name='img',
            field=models.ImageField(upload_to=''),
        ),
    ]
